export type TraitTag = 
  | "MARINE" | "HIGH_TEMP" | "FOOD_GRADE" | "HIGH_STRESS" | "BUDGET" 
  | "AUTOMOTIVE" | "AEROSPACE" | "MEDICAL" | "CRYOGENIC" | "CORROSIVE" 
  | "AESTHETIC" | "MACHINABLE" | "WELDABLE" | "STRUCTURAL" | "HYGIENIC"
  | "CHEMICAL" | "WEAR_RESISTANT" | "PRESSURE" | "ARCHITECTURAL" | "EXHAUST";

export interface SteelGrade {
  typicalApplications?: string;
  grade: string;
  type: "Austenitic" | "Ferritic" | "Martensitic" | "Duplex" | "Precipitation Hardening";
  description: string;
  yieldStrengthMpa: number;
  tensileStrengthMpa: number;
  maxTempC: number;
  pren: number;
  weldability: 1 | 2 | 3 | 4 | 5;
  machinability: 1 | 2 | 3 | 4 | 5;
  costTier: 1 | 2 | 3 | 4 | 5;
  image: string;
  composition: Record<string, string>;
}

export const steelGrades: SteelGrade[] = [
  {
    grade: "304",
    typicalApplications: "Kitchen equipment, architecture, food processing, general fabrication, railings",
    type: "Austenitic",
    description: "The most versatile and widely used stainless steel, offering excellent corrosion resistance and formability.",
    yieldStrengthMpa: 205,
    tensileStrengthMpa: 515,
    maxTempC: 870,
    pren: 18,
    weldability: 5,
    machinability: 3,
    costTier: 2,
    image: "/grade images/304/image.png",
    composition: {"C":"0.08% max","Cr":"18.0-20.0%","Ni":"8.0-10.5%","Mn":"2.0% max"}, 
  },
  {
    grade: "304L",
    typicalApplications: "Welded pressure vessels, pharma/chemical equipment, heavy-weld assemblies",
    type: "Austenitic",
    description: "Low-carbon version of 304, minimizing carbide precipitation during welding for heavy-gauge components.",
    yieldStrengthMpa: 170,
    tensileStrengthMpa: 485,
    maxTempC: 425,
    pren: 18,
    weldability: 5,
    machinability: 3,
    costTier: 2,
    image: "/grade images/304L/image.png",
    composition: {"C":"0.03% max","Cr":"18.0-20.0%","Ni":"8.0-12.0%","Mn":"2.0% max"}, 
  },
  {
    grade: "316",
    typicalApplications: "Marine hardware, chemical processing, coastal architecture, medical instruments",
    type: "Austenitic",
    description: "Standard molybdenum-bearing grade, excellent for marine environments and harsh chemical exposure.",
    yieldStrengthMpa: 205,
    tensileStrengthMpa: 515,
    maxTempC: 870,
    pren: 24,
    weldability: 4,
    machinability: 3,
    costTier: 3,
    image: "/grade images/316/image.png",
    composition: {"C":"0.08% max","Cr":"16.0-18.0%","Ni":"10.0-14.0%","Mo":"2.0-3.0%"}, 
  },
  {
    grade: "316L",
    typicalApplications: "Pharmaceutical/surgical equipment, offshore fittings, welded marine components",
    type: "Austenitic",
    description: "Molybdenum-alloyed low-carbon steel offering exceptional pitting and crevice corrosion resistance in chloride environments.",
    yieldStrengthMpa: 170,
    tensileStrengthMpa: 485,
    maxTempC: 870,
    pren: 24,
    weldability: 5,
    machinability: 3,
    costTier: 3,
    image: "/grade images/316L/image.png",
    composition: {"C":"0.03% max","Cr":"16.0-18.0%","Ni":"10.0-14.0%","Mo":"2.0-3.0%"}, 
  },
  {
    grade: "321",
    typicalApplications: "Exhaust manifolds, aerospace ducting, high-temperature chemical equipment",
    type: "Austenitic",
    description: "Titanium-stabilized austenitic steel, highly resistant to intergranular corrosion after high-temperature exposure.",
    yieldStrengthMpa: 205,
    tensileStrengthMpa: 515,
    maxTempC: 900,
    pren: 18,
    weldability: 5,
    machinability: 3,
    costTier: 3,
    image: "/grade images/321/image.png",
    composition: {"C":"0.08% max","Cr":"17.0-19.0%","Ni":"9.0-12.0%","Ti":"5x(C+N) min"}, 
  },
  {
    grade: "347",
    type: "Austenitic",
    description: "Columbium-stabilized grade ideal for high-stress, high-temperature applications like heavy exhaust components.",
    yieldStrengthMpa: 205,
    tensileStrengthMpa: 515,
    maxTempC: 870,
    pren: 19,
    weldability: 5,
    machinability: 3,
    costTier: 4,
    image: "/grade images/347/image.png",
    composition: {"C":"0.08% max","Cr":"17.0-19.0%","Ni":"9.0-13.0%","Nb":"10xC min"}, 
  },
  {
    grade: "310S",
    typicalApplications: "Furnace components, radiant tubes, heat exchangers, incinerator liners",
    type: "Austenitic",
    description: "High chromium and nickel content gives this grade incredible high-temperature oxidation resistance.",
    yieldStrengthMpa: 205,
    tensileStrengthMpa: 515,
    maxTempC: 1150,
    pren: 25,
    weldability: 4,
    machinability: 3,
    costTier: 5,
    image: "/grade images/310S/image.png",
    composition: {"C":"0.08% max","Cr":"24.0-26.0%","Ni":"19.0-22.0%","Mn":"2.0% max"}, 
  },
  {
    grade: "904L",
    typicalApplications: "Sulfuric acid handling, flue-gas desulfurization, aggressive-chloride chemical/offshore plants",
    type: "Austenitic",
    description: "Super-austenitic stainless steel designed for moderate to high corrosion resistance, especially to sulfuric acid.",
    yieldStrengthMpa: 220,
    tensileStrengthMpa: 490,
    maxTempC: 400,
    pren: 34,
    weldability: 4,
    machinability: 2,
    costTier: 5,
    image: "/grade images/904L/image.png",
    composition: {"C":"0.02% max","Cr":"19.0-23.0%","Ni":"23.0-28.0%","Mo":"4.0-5.0%","Cu":"1.0-2.0%"}, 
  },
  {
    grade: "409",
    typicalApplications: "Automotive exhaust systems, heat shields, non-critical structural trim",
    type: "Ferritic",
    description: "A titanium-stabilized ferritic steel designed primarily for automotive exhaust systems.",
    yieldStrengthMpa: 170,
    tensileStrengthMpa: 380,
    maxTempC: 815,
    pren: 11,
    weldability: 4,
    machinability: 4,
    costTier: 1,
    image: "/grade images/409/image.png",
    composition: {"C":"0.08% max","Cr":"10.5-11.7%","Ti":"6xC min","Mn":"1.0% max"}, 
  },
  {
    grade: "430",
    typicalApplications: "Kitchen appliance panels, automotive trim, indoor/dry architectural cladding",
    type: "Ferritic",
    description: "A basic ferritic non-hardenable steel with good corrosion resistance and formability, mostly used indoors.",
    yieldStrengthMpa: 310,
    tensileStrengthMpa: 450,
    maxTempC: 815,
    pren: 16,
    weldability: 2,
    machinability: 4,
    costTier: 1,
    image: "/grade images/430/image.png",
    composition: {"C":"0.12% max","Cr":"16.0-18.0%","Mn":"1.0% max"}, 
  },
  {
    grade: "439",
    typicalApplications: "Automotive exhaust, water heaters, architectural trim needing better welds than 409",
    type: "Ferritic",
    description: "Titanium stabilized ferritic grade offering better high-temperature oxidation and corrosion resistance than 409.",
    yieldStrengthMpa: 240,
    tensileStrengthMpa: 430,
    maxTempC: 850,
    pren: 18,
    weldability: 4,
    machinability: 4,
    costTier: 2,
    image: "/grade images/439/image.png",
    composition: {"C":"0.03% max","Cr":"17.0-19.0%","Ti":"0.2-1.1%"}, 
  },
  {
    grade: "441",
    type: "Ferritic",
    description: "Dual-stabilized (Ti+Nb) ferritic steel used for extreme heat applications like catalytic converter mesh.",
    yieldStrengthMpa: 250,
    tensileStrengthMpa: 430,
    maxTempC: 950,
    pren: 18,
    weldability: 4,
    machinability: 4,
    costTier: 2,
    image: "/grade images/441/image.png",
    composition: {"C":"0.03% max","Cr":"17.5-19.5%","Ti":"0.1-0.5%","Nb":"0.3-0.9%"}, 
  },
  {
    grade: "444",
    type: "Ferritic",
    description: "Molybdenum-alloyed ferritic steel matching the pitting resistance of 316, excellent for hot water tanks.",
    yieldStrengthMpa: 275,
    tensileStrengthMpa: 415,
    maxTempC: 850,
    pren: 24,
    weldability: 3,
    machinability: 4,
    costTier: 3,
    image: "/grade images/444/image.png",
    composition: {"C":"0.025% max","Cr":"17.5-19.5%","Mo":"1.75-2.50%"}, 
  },
  {
    grade: "410S",
    type: "Ferritic",
    description: "Low-carbon, non-hardening modification of 410, providing good oxidation resistance and moderate strength.",
    yieldStrengthMpa: 205,
    tensileStrengthMpa: 415,
    maxTempC: 705,
    pren: 12,
    weldability: 3,
    machinability: 4,
    costTier: 1,
    image: "/grade images/410S/image.png",
    composition: {"C":"0.08% max","Cr":"11.5-13.5%","Mn":"1.0% max"}, 
  },
  {
    grade: "2205",
    type: "Duplex",
    description: "A highly engineered duplex steel combining high strength with excellent stress-corrosion cracking resistance.",
    yieldStrengthMpa: 450,
    tensileStrengthMpa: 620,
    maxTempC: 300,
    pren: 35,
    weldability: 4,
    machinability: 2,
    costTier: 4,
    image: "/grade images/2205/image.png",
    composition: {"C":"0.03% max","Cr":"22.0-23.0%","Ni":"4.5-6.5%","Mo":"3.0-3.5%","N":"0.14-0.20%"}, 
  },
  {
    grade: "2507",
    type: "Duplex",
    description: "Super Duplex grade designed for highly corrosive environments requiring extreme strength and chloride resistance.",
    yieldStrengthMpa: 550,
    tensileStrengthMpa: 795,
    maxTempC: 315,
    pren: 42,
    weldability: 3,
    machinability: 2,
    costTier: 5,
    image: "/grade images/2507/image.png",
    composition: {"C":"0.03% max","Cr":"24.0-26.0%","Ni":"6.0-8.0%","Mo":"3.0-5.0%","N":"0.24-0.32%"}, 
  },
  {
    grade: "17-4PH",
    type: "Precipitation Hardening",
    description: "Precipitation-hardening martensitic stainless steel delivering high strength and hardness along with excellent corrosion resistance.",
    yieldStrengthMpa: 1170,
    tensileStrengthMpa: 1310,
    maxTempC: 315,
    pren: 16,
    weldability: 3,
    machinability: 3,
    costTier: 5,
    image: "/grade images/17-4PH/image.png",
    composition: {"C":"0.07% max","Cr":"15.0-17.5%","Ni":"3.0-5.0%","Cu":"3.0-5.0%","Nb":"0.15-0.45%"}, 
  }
,
  {
      "grade": "201",
      "type": "Austenitic",
      "description": "A lower-cost alternative to 304, using manganese and nitrogen to replace some nickel. Suitable for indoor applications.",
      "yieldStrengthMpa": 310,
      "tensileStrengthMpa": 750,
      "maxTempC": 350,
      "pren": 14,
      "weldability": 3,
      "machinability": 3,
      "costTier": 2,
      "image": "/grade images/304/image.png",
      "composition": {
          "C": "0.15% max",
          "Cr": "16.0-18.0%",
          "Ni": "3.5-5.5%",
          "Mn": "5.5-7.5%",
          "N": "0.25% max"
      }
  },
  {
      "grade": "202",
      "type": "Austenitic",
      "description": "Slightly higher nickel content than 201, providing marginally better corrosion resistance but still primarily for indoor use.",
      "yieldStrengthMpa": 260,
      "tensileStrengthMpa": 655,
      "maxTempC": 350,
      "pren": 15,
      "weldability": 3,
      "machinability": 3,
      "costTier": 2,
      "image": "/grade images/304L/image.png",
      "composition": {
          "C": "0.15% max",
          "Cr": "17.0-19.0%",
          "Ni": "4.0-6.0%",
          "Mn": "7.5-10.0%",
          "N": "0.25% max"
      }
  }
];


export function getGradeData(gradeName: string): SteelGrade | undefined {
  return steelGrades.find(g => g.grade.toUpperCase() === gradeName.toUpperCase());
}
